name: GitHub Actions Demo

on:
  # webhook events
  push:
    branches:
      - main
    paths-ignore:
      .github/**
  workflow_dispatch:
  pull_request:
    branches: [ main ] 
  
  schedule:
    - cron: '15 6 * * 0'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hi"
      - run: echo $GITHUB_EVENT_NAME
      - run: echo $GITHUB_REF_NAME
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
    


    
  
      
