name: GitHub Actions Demo

on:
  # webhook events
  push:
    branches:
      - main
    paths-ignore:
      .github/**
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
  pull_request:
    branches: [ main ] 
    
  #schedule:
    #- cron: '15 6 * * 0'
    
jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    needs: [build]
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Print test output
        run: echo "Testing ..."
      - name: Print event name
        run: echo "Event name ${{ github.event_name }}"

  load-test:
    runs-on: ubuntu-latest
    environment: load-test
    needs: [build]
    if: github.event_name == 'workflow_dispatch'
    #if: 1 == 2
    
    steps:
      - name: Print load-test output
        run: echo "Load-Testing ..."
      - name: Sleep 15 sec
        run: sleep 15
      - name: Echo event name 
        run: |
          echo "Event name ${{ github.event_name }}"
          echo ${{ github.event_name }} == workflow_d
        
  production:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        step: [1, 2, 3, 4, 5]
    environment: production
    needs: [test, load-test]
    if: github.event.inputs.environment == 'load-test'
    
    steps:
      - name: Print Step
        run: echo ${{ matrix.step }}

        
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Hi"
      - run: echo $GITHUB_EVENT_NAME
      - run: echo ${{ github.event_name }}
      - run: echo $GITHUB_REF_NAME
      - run: echo ${{ github.ref }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump github context
        run: echo '${{ toJSON(github) }}'
  
    


    
  
      
